---
# tasks file for elasticsearch
  - apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present
  - apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main'
  - name: update package
    apt: update_cache=yes
  - name: install elasticsearch
    apt: name=elasticsearch state=present update_cache=yes
  - name: copy elasticsearch.yml file
    template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
    notify: start elasticsearch

